//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-MVVM-Coordinator-template
//

import Foundation
import SwiftUI

// MARK: - ___VARIABLE_moduleName___ModuleInput
protocol ___VARIABLE_moduleName___ModuleInput: AnyObject { }

// MARK: - ___VARIABLE_moduleName___ModuleOutput
struct ___VARIABLE_moduleName___ModuleOutput {
    
//    let didSelectSearchResult: (_ searchResult: String) -> Void
}
