//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-MVVM-Coordinator-template
//

import UIKit
import SwiftUI
import uCore

struct ___VARIABLE_productName:identifier___Configurator {

    typealias Dependencies = identifier___ViewModel.Dependencies

    static func createModule(
        dependencies: Dependencies
        output: ___VARIABLE_productName:identifier___ModuleOutput? = nil
    ) -> (view: some View & Coordinating, input: ___VARIABLE_productName:identifier___ModuleInput) {
        let viewModel = ___VARIABLE_productName:identifier___ViewModel(dependencies: dependencies, output: output)
        let view = ___VARIABLE_productName:identifier___Screen(viewModel: viewModel)

        return (view, viewModel)
    }
}
