//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-MVVM-Coordinator-template
//

import SwiftUI
import uCore

struct ___VARIABLE_productName:identifier___Screen: View, Coordinating {

    @StateObject var viewModel: ___VARIABLE_productName:identifier___ViewModel
    var coordinator: Coordinatable?

    var body: some View {
        Text("Hello")
    }
}

#Preview {
    class Dependencies: identifier___Configurator.Dependencies {

    }
    let module = ___VARIABLE_productName:identifier___Configurator.createModule(dependencies: Dependencies)
    return module.view
}
